name: Last Release

on: [pull_request, release]

jobs:
  tests:
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure ULTERA MongoDB Access
      run: echo "$PYQALLOYSTATICCONFIG" > pyqalloy/credentials.json
      shell: bash
      env:
        PYQALLOYSTATICCONFIG: ${{secrets.PYQALLOYSTATICCONFIG}}
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: 'pyproject.toml'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flask pytest pytest-cov
        python -m pip install -e .
        
    - name: Test with pytest
      run: |
        pytest --cov=pyqalloy --cov-report=xml

  coverage-python310:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure ULTERA MongoDB Access
        run: echo "$PYQALLOYSTATICCONFIG" > pyqalloy/credentials.json
        shell: bash
        env:
          PYQALLOYSTATICCONFIG: ${{secrets.PYQALLOYSTATICCONFIG}}
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flask pytest pytest-cov
          python -m pip install -e .

      - name: Test with pytest
        run: |
          pytest --cov=pyqalloy --cov-report=xml

      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
