name: Python package

on: [push, pull_request, release]

jobs:
  tests:
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: '**/pyproject.toml'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flask pytest pytest-cov
        python -m pip install -e .
    
    - name: Configure ULTERA MongoDB Access
      run: |
        'echo "$PYQALLOYSTATICCONFIG" > pyqalloy/credentials.json'
      shell: bash
      env:
        PYQALLOYSTATICCONFIG: ${{secrets.PYQALLOYSTATICCONFIG}}
        
    - name: Test with pytest
      run: |
        pytest --cov=pyqalloy --cov-report=xml
    - name: Upload pytest test results
      uses: actions/upload-artifact@v3

  Upload-Coverage:
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      # The source code _must_ be checked out for coverage to be processed at Codecov.
      - uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
